name: TestOnPush

env:
  # Force the stdout and stderr streams to be unbuffered
  PYTHONUNBUFFERED: 1

on: # yamllint disable-line rule:truthy
  push:
    tags: '**'
  workflow_dispatch:

jobs:
  Echo:
    runs-on: ubuntu-latest
    steps:
    - name: Out GITHUB_REF
      run: |
        echo "GITHUB_REF: ${GITHUB_REF}"
        echo "GITHUB_REF#refs/tags/: ${GITHUB_REF#refs/tags/}"
