name: TestOnPush

env:
  # Force the stdout and stderr streams to be unbuffered
  PYTHONUNBUFFERED: 1

on: # yamllint disable-line rule:truthy
  push:
    tags: '**'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Test scenario tag'
        required: true 
        type: string

jobs:
  Echo:
    runs-on: ubuntu-latest
    steps:
    - name: Set test tag
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "GITHUB_TAG=${{ inputs.tag }}" >> "$GITHUB_ENV"
    - name: Get tag name
      if: github.event_name != 'workflow_dispatch'
      run: |
        echo "GITHUB_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
      
    - name: Out GITHUB_TAG
      run: |
        echo "GITHUB_REF: ${GITHUB_REF}"
        echo "GITHUB_TAG: ${GITHUB_TAG}"
