name: PullRequestCI
on:
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
    paths-ignore:
      - 'ignore/**'
jobs:
  Init:
    runs-on: ubuntu-latest
    env:
      SOMETHING: ${{ secrets.SOMETHING }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade PyGithub
      - name: Run my_init.py
        run: |
          cd "$GITHUB_WORKSPACE/tests/ci"
          python3 my_init.py
  CheckLabels:
    needs: Init
    runs-on: ubuntu-latest
    steps:
      - name: Labels check
        run: exit 0
  StyleCheck:
    needs: CheckLabels
    runs-on: ubuntu-latest
    steps:
      - name: Style check
        run: exit 1
